[platformio]
default_envs = esp32-s3-devkitc-1-n16r8
extra_configs =
    src/Hal/Boards/board_configs/cyd.ini
    src/Hal/Boards/board_configs/t_hmi.ini
    src/Hal/Boards/board_configs/cardputer.ini

; Global OS configuration shared across all boards
[env]
build_flags =
    -D KRYONOS_VERSION=\"2.0.0\"
    -D KRYONOS_API_LEVEL=2
    -D CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=1

[env:esp32-s3-devkitc-1-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv

monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson @ 7.1.0
    mathieucarbou/ESPAsyncWebServer @ 3.1.5
    links2004/WebSockets @ ^2.4.1

build_flags =
    ${env.build_flags}
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -D CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=1
    -D ARDUINO_LOOP_STACK_SIZE=32768
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D USER_SETUP_LOADED=1
    -D USE_HSPI_PORT=1
    -D ILI9341_DRIVER=1
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=8
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TOUCH_CS=7
    -D TOUCH_CLK=4
    -D TOUCH_DIN=5
    -D TOUCH_DO=6
    -D TOUCH_IRQ=14
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv

monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson @ 7.1.0
    mathieucarbou/ESPAsyncWebServer @ 3.1.5
    links2004/WebSockets @ ^2.4.1

build_flags =
    ${env.build_flags}
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=17
    -D TFT_DC=16
    -D TFT_RST=5
    -D TOUCH_CS=21
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
